baseURL = "http://example.org/"
languageCode = "en-us"
title = "SH Dev Blog"
theme = "harbor"
author = "Steve Francia"
paginate = 3
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[Author]
  name = "SeHwan Dev"

[permalinks]
	post = "/:year/:month/:day/:filename/"
	page = "/:filename/"

[outputs]
    section = ["JSON", "HTML"]

[[params.nav]]
  identifier = "about"
  name = "About"
  icon = "fas fa-user fa-lg"
  url = "/about/"
  weight = 3

[[params.nav]]
  identifier = "tags"
  name = "Tags"
  icon = "fas fa-tag fa-lg"
  url = "/tags/"
  weight = 3

[[params.nav]]
  identifier = "search"
  name = "Search"
  icon = "fas fa-search fa-lg"
  url = "/search/"
  weight = 3

[[params.social]]
  name= "Twitter"
  url="https://twitter.com/GoHugoIO"
  icon="fab fa-twitter"

[[params.social]]
  name= "GitHub"
  url="https://github.com/gohugoio/hugo"
  icon="fab fa-github"


[params]
  mainSections = ["post"]
  favicon = "favicon.ico"

  [params.logo]
    url = "icon.png"
    width = 50
    height = 50
    alt = "Logo"